export const allCountriesData: any = {
  afghanistan: "af",
  albania: "al",
  algeria: "dz",
  "american samoa": "as",
  andorra: "ad",
  angola: "ao",
  anguilla: "ai",
  antarctica: "aq",
  "antigua and barbuda": "ag",
  argentina: "ar",
  armenia: "am",
  aruba: "aw",
  australia: "au",
  austria: "at",
  azerbaijan: "az",
  "bahamas (the)": "bs",
  bahrain: "bh",
  bangladesh: "bd",
  barbados: "bb",
  belarus: "by",
  belgium: "be",
  belize: "bz",
  benin: "bj",
  bermuda: "bm",
  bhutan: "bt",
  "bolivia (plurinational state of)": "bo",
  "bonaire, sint eustatius and saba": "bq",
  "bosnia and herzegovina": "ba",
  botswana: "bw",
  "bouvet island": "bv",
  brazil: "br",
  "british indian ocean territory (the)": "io",
  "brunei darussalam": "bn",
  bulgaria: "bg",
  "burkina faso": "bf",
  burundi: "bi",
  "cabo verde": "cv",
  cambodia: "kh",
  cameroon: "cm",
  canada: "ca",
  "cayman islands (the)": "ky",
  "central african republic (the)": "cf",
  chad: "td",
  chile: "cl",
  china: "cn",
  "christmas island": "cx",
  "cocos (keeling) islands (the)": "cc",
  colombia: "co",
  "comoros (the)": "km",
  "congo (the democratic republic of the)": "cd",
  "congo (the)": "cg",
  "cook islands (the)": "ck",
  "costa rica": "cr",
  croatia: "hr",
  cuba: "cu",
  curaçao: "cw",
  cyprus: "cy",
  czechia: "cz",
  "côte d'ivoire": "ci",
  denmark: "dk",
  djibouti: "dj",
  dominica: "dm",
  "dominican republic (the)": "do",
  ecuador: "ec",
  egypt: "eg",
  "el salvador": "sv",
  "equatorial guinea": "gq",
  eritrea: "er",
  estonia: "ee",
  eswatini: "sz",
  ethiopia: "et",
  "falkland islands (the) [malvinas]": "fk",
  "faroe islands (the)": "fo",
  fiji: "fj",
  finland: "fi",
  france: "fr",
  "french guiana": "gf",
  "french polynesia": "pf",
  "french southern territories (the)": "tf",
  gabon: "ga",
  "gambia (the)": "gm",
  georgia: "ge",
  germany: "de",
  ghana: "gh",
  gibraltar: "gi",
  greece: "gr",
  greenland: "gl",
  grenada: "gd",
  guadeloupe: "gp",
  guam: "gu",
  guatemala: "gt",
  guernsey: "gg",
  guinea: "gn",
  "guinea-bissau": "gw",
  guyana: "gy",
  haiti: "ht",
  "heard island and mcdonald islands": "hm",
  "holy see (the)": "va",
  honduras: "hn",
  "hong kong": "hk",
  hungary: "hu",
  iceland: "is",
  india: "in",
  indonesia: "id",
  "iran (islamic republic of)": "ir",
  iraq: "iq",
  ireland: "ie",
  "isle of man": "im",
  israel: "il",
  italy: "it",
  jamaica: "jm",
  japan: "jp",
  jersey: "je",
  jordan: "jo",
  kazakhstan: "kz",
  kenya: "ke",
  kiribati: "ki",
  "korea (the democratic people's republic of)": "kp",
  "korea (the republic of)": "kr",
  kuwait: "kw",
  kyrgyzstan: "kg",
  "lao people's democratic republic (the)": "la",
  latvia: "lv",
  lebanon: "lb",
  lesotho: "ls",
  liberia: "lr",
  libya: "ly",
  liechtenstein: "li",
  lithuania: "lt",
  luxembourg: "lu",
  macao: "mo",
  madagascar: "mg",
  malawi: "mw",
  malaysia: "my",
  maldives: "mv",
  mali: "ml",
  malta: "mt",
  "marshall islands (the)": "mh",
  martinique: "mq",
  mauritania: "mr",
  mauritius: "mu",
  mayotte: "yt",
  mexico: "mx",
  "micronesia (federated states of)": "fm",
  "moldova (the republic of)": "md",
  monaco: "mc",
  mongolia: "mn",
  montenegro: "me",
  montserrat: "ms",
  morocco: "ma",
  mozambique: "mz",
  myanmar: "mm",
  namibia: "na",
  nauru: "nr",
  nepal: "np",
  "netherlands (the)": "nl",
  "new caledonia": "nc",
  "new zealand": "nz",
  nicaragua: "ni",
  "niger (the)": "ne",
  nigeria: "ng",
  niue: "nu",
  "norfolk island": "nf",
  "northern mariana islands (the)": "mp",
  norway: "no",
  oman: "om",
  pakistan: "pk",
  palau: "pw",
  "palestine, state of": "ps",
  panama: "pa",
  "papua new guinea": "pg",
  paraguay: "py",
  peru: "pe",
  "philippines (the)": "ph",
  pitcairn: "pn",
  poland: "pl",
  portugal: "pt",
  "puerto rico": "pr",
  qatar: "qa",
  "republic of north macedonia": "mk",
  romania: "ro",
  "russian federation (the)": "ru",
  rwanda: "rw",
  réunion: "re",
  "saint barthélemy": "bl",
  "saint helena, ascension and tristan da cunha": "sh",
  "saint kitts and nevis": "kn",
  "saint lucia": "lc",
  "saint martin (french part)": "mf",
  "saint pierre and miquelon": "pm",
  "saint vincent and the grenadines": "vc",
  samoa: "ws",
  "san marino": "sm",
  "sao tome and principe": "st",
  "saudi arabia": "sa",
  senegal: "sn",
  serbia: "rs",
  seychelles: "sc",
  "sierra leone": "sl",
  singapore: "sg",
  "sint maarten (dutch part)": "sx",
  slovakia: "sk",
  slovenia: "si",
  "solomon islands": "sb",
  somalia: "so",
  "south africa": "za",
  "south georgia and the south sandwich islands": "gs",
  "south sudan": "ss",
  spain: "es",
  "sri lanka": "lk",
  "sudan (the)": "sd",
  suriname: "sr",
  "svalbard and jan mayen": "sj",
  sweden: "se",
  switzerland: "ch",
  "syrian arab republic": "sy",
  taiwan: "tw",
  tajikistan: "tj",
  "tanzania, united republic of": "tz",
  thailand: "th",
  "timor-leste": "tl",
  togo: "tg",
  tokelau: "tk",
  tonga: "to",
  "trinidad and tobago": "tt",
  tunisia: "tn",
  turkey: "tr",
  turkmenistan: "tm",
  "turks and caicos islands (the)": "tc",
  tuvalu: "tv",
  uganda: "ug",
  ukraine: "ua",
  "united arab emirates (the)": "ae",
  "united kingdom of great britain and northern ireland (the)": "gb",
  "united states minor outlying islands (the)": "um",
  "united states of america (the)": "us",
  uruguay: "uy",
  uzbekistan: "uz",
  vanuatu: "vu",
  "venezuela (bolivarian republic of)": "ve",
  "viet nam": "vn",
  "virgin islands (british)": "vg",
  "virgin islands (u.s.)": "vi",
  "wallis and futuna": "wf",
  "western sahara": "eh",
  yemen: "ye",
  zambia: "zm",
  zimbabwe: "zw",
  "åland islands": "ax",
};
export const countries_code: any = {
  abkhazia: 7,
  afghanistan: 93,
  albania: 355,
  algeria: 213,
  "american samoa": 1,
  andorra: 376,
  angola: 244,
  anguilla: 1,
  "antigua and barbuda": 1,
  argentina: 54,
  armenia: 374,
  aruba: 297,
  ascension: 247,
  australia: 61,
  "australian external territories": 672,
  austria: 43,
  azerbaijan: 994,
  bahamas: 1,
  bahrain: 973,
  bangladesh: 880,
  barbados: 1,
  barbuda: 1,
  belarus: 375,
  belgium: 32,
  belize: 501,
  benin: 229,
  bermuda: 1,
  bhutan: 975,
  bolivia: 591,
  "bosnia and herzegovina": 387,
  botswana: 267,
  brazil: 55,
  "british indian ocean territory": 246,
  "british virgin islands": 1,
  brunei: 673,
  bulgaria: 359,
  "burkina faso": 226,
  burundi: 257,
  cambodia: 855,
  cameroon: 237,
  canada: 1,
  "cape verde": 238,
  "cayman islands": null,
  "central african republic": 236,
  chad: 235,
  chile: 56,
  china: 86,
  "christmas island": 61,
  "cocos-keeling islands": 61,
  colombia: 57,
  comoros: 269,
  congo: 242,
  "congo, dem. rep. of (zaire)": 243,
  "cook islands": 682,
  "costa rica": 506,
  croatia: 385,
  cuba: 53,
  curacao: 599,
  cyprus: 537,
  "czech republic": 420,
  denmark: 45,
  "diego garcia": 246,
  djibouti: 253,
  dominica: 1,
  "dominican republic": 1,
  "east timor": 670,
  "easter island": 56,
  ecuador: 593,
  egypt: 20,
  "el salvador": 503,
  "equatorial guinea": 240,
  eritrea: 291,
  estonia: 372,
  ethiopia: 251,
  "falkland islands": 500,
  "faroe islands": 298,
  fiji: 679,
  finland: 358,
  france: 33,
  "french antilles": 596,
  "french guiana": 594,
  "french polynesia": 689,
  gabon: 241,
  gambia: 220,
  georgia: 995,
  germany: 49,
  ghana: 233,
  gibraltar: 350,
  greece: 30,
  greenland: 299,
  grenada: 1,
  guadeloupe: 590,
  guam: 1,
  guatemala: 502,
  guinea: 224,
  "guinea-bissau": 245,
  guyana: 595,
  haiti: 509,
  honduras: 504,
  "hong kong sar china": 852,
  hungary: 36,
  iceland: 354,
  india: 91,
  indonesia: 62,
  iran: 98,
  iraq: 964,
  ireland: 353,
  israel: 972,
  italy: 39,
  "ivory coast": 225,
  jamaica: 1,
  japan: 81,
  jordan: 962,
  kazakhstan: 7,
  kenya: 254,
  kiribati: 686,
  kuwait: 965,
  kyrgyzstan: 996,
  laos: 856,
  latvia: 371,
  lebanon: 961,
  lesotho: 266,
  liberia: 231,
  libya: 218,
  liechtenstein: 423,
  lithuania: 370,
  luxembourg: 352,
  "macau sar china": 853,
  macedonia: 389,
  madagascar: 261,
  malawi: 265,
  malaysia: 60,
  maldives: 960,
  mali: 223,
  malta: 356,
  "marshall islands": 692,
  martinique: 596,
  mauritania: 222,
  mauritius: 230,
  mayotte: 262,
  mexico: 52,
  micronesia: 691,
  "midway island": 1,
  moldova: 373,
  monaco: 377,
  mongolia: 976,
  montenegro: 382,
  montserrat: 1664,
  morocco: 212,
  myanmar: 95,
  namibia: 264,
  nauru: 674,
  nepal: 977,
  netherlands: 31,
  "netherlands antilles": 599,
  nevis: 1,
  "new caledonia": 687,
  "new zealand": 64,
  nicaragua: 505,
  niger: 227,
  nigeria: 234,
  niue: 683,
  "norfolk island": 672,
  "north korea": 850,
  "northern mariana islands": 1,
  norway: 47,
  oman: 968,
  pakistan: 92,
  palau: 680,
  "palestinian territory": 970,
  panama: 507,
  "papua new guinea": 675,
  paraguay: 595,
  peru: 51,
  philippines: 63,
  poland: 48,
  portugal: 351,
  "puerto rico": 1,
  qatar: 974,
  reunion: 262,
  romania: 40,
  russia: 7,
  rwanda: 250,
  samoa: 685,
  "san marino": 378,
  "saudi arabia": 966,
  senegal: 221,
  serbia: 381,
  seychelles: 248,
  "sierra leone": 232,
  singapore: 65,
  slovakia: 421,
  slovenia: 386,
  "solomon islands": 677,
  "south africa": 27,
  "south georgia and the south sandwich islands": 500,
  "south korea": 82,
  spain: 34,
  "sri lanka": 94,
  sudan: 249,
  suriname: 597,
  swaziland: 268,
  sweden: 46,
  switzerland: 41,
  syria: 963,
  taiwan: 886,
  tajikistan: 992,
  tanzania: 255,
  thailand: 66,
  "timor leste": 670,
  togo: 228,
  tokelau: 690,
  tonga: 676,
  "trinidad and tobago": 1,
  tunisia: 216,
  turkey: 90,
  turkmenistan: 993,
  "turks and caicos islands": 1,
  tuvalu: 688,
  "u.s. virgin islands": 1,
  uganda: 256,
  ukraine: 380,
  "united arab emirates": 971,
  "united kingdom": 44,
  "united states": 1,
  uruguay: 598,
  uzbekistan: 998,
  vanuatu: 678,
  venezuela: 58,
  vietnam: 84,
  "wake island": 1,
  "wallis and futuna": 681,
  yemen: 967,
  zambia: 260,
  zanzibar: 255,
  zimbabwe: 263,
};
